### ISSUE TITLE
[Bug] xtensor Input tensor is not a lazy tensor: CPUFloatType

### ISSUE THREAD

**Issue by comaniac** [awslabs/ratex#42]
Error:
```
[F aten_ltc_bridge.cpp:76] Check failed: xtensor Input tensor is not a lazy tensor: CPUFloatType
```

How to reproduce (with `meta-project/models`):
```
python3 -m benchmark bench --framework torch --model bert_test_mlm --batch 32 --ltc ratex --workload "512" --optimizer Adam
```

I did a high-level diagnosis and the problem comes from #36.

cc @hgt312 @hzfan

**Comment by zachzzc** [comment]
#28 is just about adding the document. how did this bring problems ?

**Comment by comaniac** [comment]
Sorry I put the wrong reference. I meant #36
